version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autoreel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/autoreel?schema=public
      - REDIS_URL=redis://redis:6379
      # Cấu hình SMTP để gửi mail đăng nhập (Khách tự điền)
      - EMAIL_SERVER=smtp://username:password@smtp.gmail.com:587
      - EMAIL_FROM=noreply@example.com
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=local_secret_key_12345
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: node dist/worker.js
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/autoreel?schema=public
      - REDIS_URL=redis://redis:6379
      - EMAIL_SERVER=smtp://username:password@smtp.gmail.com:587
      - EMAIL_FROM=noreply@example.com
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=local_secret_key_12345
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
